name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 black  # Установите нужные пакеты

      - name: Run linters
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # Проверка ошибок синтаксиса
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  # Дополнительные проверки
          black . --check  # Проверка форматирования

      - name: Run tests
        run: |
          pytest --cov=app --cov-report=term-missing  # Запуск тестов с покрытием
